Feat/gitbackup
Kibnet/Unlimotion pull request #100
Opened 2023-11-07 17:34 UTC by Scorfox

2023-11-08 08:19 UTC, Kibnet requested changes
Надо ещё сделать pull.
Также лучше переделать на работу по времени, а не после каждого изменения

2023-11-13 19:59 UTC, Kibnet requested changes
Что точно стоит поправить:
1. Запечатывание настроек заменить на доставание из конфига в момент использования
2. Сделать невозможным одновременный запуск push и pull

2023-11-13 19:59 UTC, Kibnet commented on src/Unlimotion.Desktop/Program.cs
> +                    repositoryPath));
Кажется что в этом месте мы запечатываем настройки и чтобы применились значения введёные в настройках придётся перезапустить приложение. А хочется чтобы изменения применились сразу. Для этого как раз и используется конструкция доставания настроек
`configuration.Get<TaskStorageSettings>("TaskStorage");`
в ней каждый раз будет доставаться текущее значение

2023-11-13 19:59 UTC, Kibnet commented on src/Unlimotion.Desktop/Program.cs
> +                    taskStorageSettings.GitPushIntervalSeconds);
Тут та же фигня с запечатыванием настроек. То есть нужно будет перезапустить. Тут вижу 2 варианта:
1. Реагировать на изменение этих параметров и пересоздавать задачи
2. Сделать кнопку обновления времени в настройках напротив полей ввода

2023-11-13 19:59 UTC, Kibnet commented on src/Unlimotion.ViewModel/TaskStorageSettings.cs
> +    public bool GitBackupEnabled { get; set; }
Эти настройки так и просятся в отдельный раздел

2023-11-13 19:59 UTC, Kibnet commented on src/Unlimotion/Services/BackupViaGitService.cs
> +    private const string CommitterEmail = "backuper@unlimotion.ru";
Эти параметры в итоге тоже должны уехать в настройки

2023-11-13 19:59 UTC, Kibnet commented on src/Unlimotion/Services/BackupViaGitService.cs
> +    }
Надо предотвратить ситуацию одновременного запуска push и pull. Например с помощью lock.

2023-11-13 19:59 UTC, Kibnet commented on src/Unlimotion/Services/BackupViaGitService.cs
> +                    Password = password
Именно тут непосредственно перед использованием нужно извлекать настройки из конфига и применять свежие значения

2023-11-14 08:24 UTC, Scorfox commented on src/Unlimotion.Desktop/Program.cs
> +                    repositoryPath));
Согласна, поменяю

2023-11-14 08:24 UTC, Scorfox commented on src/Unlimotion/Services/BackupViaGitService.cs
> +    }
По факту, сделаю

2023-11-20 05:28 UTC, Scorfox commented on src/Unlimotion/FileTaskStorage.cs
> +                new Thread(() => GitBackupService?.Push($"Removed the task with ID \"{itemId}\"")).Start();
Сделала

2023-11-20 05:28 UTC, Scorfox commented on src/Unlimotion.Desktop/Program.cs
> +                    taskStorageSettings.GitPushIntervalSeconds);
Сделала

2023-11-20 05:28 UTC, Scorfox commented on src/Unlimotion/Services/BackupViaGitService.cs
> +    private const string CommitterEmail = "backuper@unlimotion.ru";
Сделала

2023-11-20 05:28 UTC, Scorfox commented on src/Unlimotion/Services/BackupViaGitService.cs
> +    }
Сделала

2023-11-20 05:28 UTC, Scorfox commented on src/Unlimotion/Services/BackupViaGitService.cs
> +                    Password = password
Сделала

2023-11-20 05:28 UTC, Scorfox commented on src/Unlimotion.ViewModel/TaskStorageSettings.cs
> +    public bool GitBackupEnabled { get; set; }
Сделала

2023-11-23 09:47 UTC, Kibnet approved these changes

2023-11-23 09:47 UTC, merged