Feat/9 add file watcher for check if files was changed outside
Kibnet/Unlimotion pull request #99
Opened 2023-10-31 18:06 UTC by Kozlov-AE

2023-10-31 20:49 UTC, Kibnet requested changes
Нужно исправить перезагрузку редактируемых в программе файлов с помощью кеша по времени 10 секунд.
Привести в порядок наименования классов, полей, свойств и переменных в соответствии с нормами английского и семантического значения

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/Models/UpdatedTask.cs
> +    public class UpdatedTask
```suggestion
    public class TaskUpdateEvent
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/Models/UpdatedTask.cs
> +        public DateTime UpdatedDateTime { get; }
```suggestion
        public DateTime EventDateTime { get; }
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/Models/UpdatedTask.cs
> +        public UpdatingTaskType UpdatingType { get; }
```suggestion
        public UpdateType Type { get; }
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/Models/UpdatingTaskType.cs
> +    public enum UpdatingTaskType
```suggestion
    public enum UpdateType
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/Models/UpdatingTaskType.cs
> +        TaskChanged
```suggestion
        Created,
        Deleted,
        Changed
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/TaskRepository.cs
> +            var isWatherAcive = _dbWatcher != null && _dbWatcher.IsEnabled;
```suggestion
            var isWatcherActive = _dbWatcher != null && _dbWatcher.IsEnabled;
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion.ViewModel/TaskRepository.cs
> +                await _dbWatcher.Start();
Вместо остановки и старта закидывать имя файла в кеш игнора для вотчера

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion/TaskStorages.cs
> +                //Locator.CurrentMutable.RegisterConstant<IDatabaseWatcher>(fileDbWather);
```suggestion
```

2023-10-31 20:49 UTC, Kibnet commented on src/Unlimotion/TaskStorages.cs
> +        private static IDatabaseWatcher _dbWatcher;
Кажется можно обойтись без статического поля, просто грамотно проинициализировав вотчер

2023-11-01 18:32 UTC, Kozlov-AE commented on src/Unlimotion/TaskStorages.cs
> +        private static IDatabaseWatcher _dbWatcher;
Нет. Он передается как зависимость в методе RegisterStorage

2023-11-07 19:15 UTC, Kibnet approved these changes
#9 close

2023-11-07 19:15 UTC, merged

2023-12-20 14:45 UTC, Kibnet commented
close #9